// Focused offline conversion and expanded-day browser regression.
const {chromium}=require('playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
  const html=fs.readFileSync(path.resolve(__dirname,'../packages/templates/trip-publish/trip.html'),'utf8');
  const browser=await chromium.launch({headless:true});
  try {
    const page=await browser.newPage({viewport:{width:390,height:844}});
    await page.setContent(html);
    assert.equal(await page.locator('.trip-teaser').count(),1);
    assert.equal(await page.locator('.glance-budget [data-money-usd]').innerText(),'US$12,000');
    assert.equal(await page.locator('.glance-budget p').count(),0);
    await page.locator('#flight-out>summary').click();
    assert.equal(await page.locator('#flight-out .flight-leg').count(),3);
    assert.match(await page.locator('#flight-out').innerText(),/DEMO-7K2M9Q/);
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedFlight=text;}}}));
    await page.locator('[data-copy-target="flight-out-ref"]').click();
    assert.equal(await page.evaluate(()=>window.copiedFlight),'DEMO-7K2M9Q');
    for(const width of [320,1440]){
      await page.setViewportSize({width,height:1000});
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
      await page.locator('#flight-out').screenshot({path:path.join(require('node:os').tmpdir(),`dasync-flight-${width}.png`)});
    }
    await page.setViewportSize({width:390,height:844});
    await page.setContent(html.replace('</select>','<option value="EUR" data-rate="0.9">EUR</option><option value="BAD" data-rate="0">Invalid</option></select>'));
    assert(await page.locator('option[value=BAD]').evaluate(option=>option.disabled));
    await page.locator('[data-currency]').selectOption('EUR');
    assert.equal(await page.locator('[data-money-usd]').first().innerText(),'EUR 10,800');
    for(let i=0;i<5;i++){
      await page.locator('[data-currency]').selectOption('JPY');
      await page.locator('[data-currency]').selectOption('USD');
    }
    assert.equal(await page.locator('[data-money-usd]').first().innerText(),'USD 12,000');
    await page.locator('[data-money-usd]').first().evaluate(n=>n.dataset.moneyUsd='0');
    await page.locator('[data-currency]').selectOption('JPY');
    assert.equal(await page.locator('[data-money-usd]').first().innerText(),'JPY 0');
    await page.locator('[data-money-usd]').first().evaluate(n=>n.dataset.moneyUsd='');
    await page.locator('[data-currency]').selectOption('USD');
    assert.equal(await page.locator('[data-money-usd]').first().innerText(),'Not yet priced');
    await page.setContent(html);
    assert.equal(await page.locator('.trip-topbar .travel-nav a').count(),5);
    assert.equal(await page.locator('.trip-head [data-money-usd]').count(),0);
    assert.equal(await page.locator('#at-a-glance .glance-budget').count(),1);
    assert.equal(await page.locator('.trip-teaser>.glance-budget').count(),1);
    assert.equal(await page.locator('#expenses>details').count(),1);
    assert.equal(await page.locator('.expense-table tbody tr').count(),10);
    assert.deepEqual(await page.locator('.expense-table thead th').allTextContents(),['Category','Line item','Calculation / basis','Estimate']);
    assert(await page.locator('.expense-table tbody tr').evaluateAll(rows=>rows.every(row=>row.cells.length===4)));
    await page.setViewportSize({width:1440,height:1000});
    assert.equal(await page.locator('.travel .layout').evaluate(n=>Math.round(n.getBoundingClientRect().width)),1200);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.locator('.trip-topbar select[aria-label="Display currency"]').count(),1);
    await page.locator('[data-currency]').focus();
    assert(await page.locator('[data-currency]').evaluate(n=>n===document.activeElement));
    await page.locator('[data-currency]').selectOption('JPY');
    assert.equal(await page.locator('[data-currency-control]').getAttribute('title'),'Currency: JPY');
    await page.locator('[data-currency]').selectOption('USD');
    assert(await page.locator('[data-theme-icon=light]').isVisible());
    await page.emulateMedia({colorScheme:'dark'});
    await page.waitForFunction(()=>!document.querySelector('[data-theme-icon=dark]').hasAttribute('hidden'));
    assert(await page.locator('[data-theme-icon=dark]').isVisible());
    await page.locator('[data-theme-toggle]').click();
    assert(await page.locator('[data-theme-icon=light]').isVisible());
    assert.equal(await page.locator('[data-theme-toggle]').getAttribute('aria-pressed'),'false');
    await page.emulateMedia({colorScheme:'light'});
    await page.locator('.travel-nav a[href="#expenses"]').click();
    await page.waitForFunction(()=>document.querySelector('.trip-topbar').classList.contains('is-scrolled'));
    assert(await page.evaluate(()=>document.querySelector('#expenses').getBoundingClientRect().top>=document.querySelector('.trip-topbar').getBoundingClientRect().bottom),'anchor heading is not covered');
    assert.equal(Math.round(await page.locator('.trip-topbar').evaluate(n=>n.getBoundingClientRect().top)),0);
    assert(await page.locator('.trip-topbar').evaluate(n=>n.classList.contains('is-scrolled')));
    assert(await page.locator('.trip-topbar').evaluate(n=>getComputedStyle(n).backdropFilter.includes('blur')));
    const sections=await page.locator('main>.section,main>footer').evaluateAll(nodes=>nodes.map(n=>n.id));
    assert.deepEqual(sections.slice(-3),['todo','expenses','metadata']);
    const expenseValues=await page.locator('[data-expense-line]').evaluateAll(nodes=>nodes.map(n=>Number(n.dataset.moneyUsd)));
    assert.equal(expenseValues.reduce((a,b)=>a+b,0),12000);
    await page.locator('#expenses details').first().locator('summary').click();
    assert(await page.locator('.expense-table').isVisible());
    assert(await page.locator('.expense-table-wrap').evaluate(n=>n.scrollWidth>n.clientWidth));
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.emulateMedia({media:'print'});
    assert(await page.locator('.expense-table-wrap').evaluate(n=>n.scrollWidth<=n.clientWidth),'expense table fits print');
    await page.emulateMedia({media:'screen'});
    await page.locator('#expenses').screenshot({path:path.join(require('node:os').tmpdir(),'dasync-expenses-mobile.png')});
    await page.locator('#expenses details').first().locator('summary').click();
    await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
    const preview=page.locator('.trip-preview');
    assert(await preview.evaluate(n=>n.scrollWidth>n.clientWidth),'route scrolls inside its region');
    await preview.focus();
    await page.keyboard.press('ArrowRight');
    await page.waitForFunction(()=>document.querySelector('.trip-preview').scrollLeft>0);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.emulateMedia({media:'print'});
    assert(await preview.evaluate(n=>n.scrollWidth<=n.clientWidth),'all route stops fit print width');
    await page.emulateMedia({media:'print',colorScheme:'dark'});
    assert.equal(await page.locator('body').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(255, 255, 255)','system-dark printing uses paper colors');
    await page.emulateMedia({media:'screen'});
    await page.emulateMedia({colorScheme:'light'});
    assert.deepEqual(await page.locator('.date-tile small').allTextContents(),['tue','wed','thr','fri','sat','sun','mon','tue','wed']);
    await page.locator('#stay-tokyo>summary').click();
    // Controlled clipboard double: no writes to the user's system clipboard.
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedText=text;}}}));
    await page.locator('[data-copy-target=stay-reference]').click();
    assert.equal(await page.evaluate(()=>window.copiedText),'DEMO-NOT-A-BOOKING');
    assert.equal(await page.locator('#stay-tokyo .copy-feedback').innerText(),'Copied to clipboard.');
    await page.locator('[data-copy-target=stay-address]').click();
    assert.equal(await page.evaluate(()=>window.copiedText),'Replace with the full destination address');
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('Denied');}}}));
    await page.locator('[data-copy-target=stay-reference]').click();
    assert((await page.locator('#stay-tokyo .copy-feedback').innerText()).startsWith('Copy unavailable.'));
    assert.equal(await page.evaluate(()=>getSelection().toString()),'DEMO-NOT-A-BOOKING');
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:undefined}));
    await page.locator('[data-copy-target=stay-address]').click();
    assert.equal(await page.evaluate(()=>getSelection().toString()),'Replace with the full destination address');
    await page.locator('#stay-tokyo>summary').click();
    await page.locator('#reservations').screenshot({path:path.join(require('node:os').tmpdir(), 'dasync-travel-reservations.png')});
    await page.locator('[data-theme-toggle]').click();
    await page.locator('#at-a-glance').screenshot({path:path.join(require('node:os').tmpdir(), 'dasync-travel-preview-dark.png')});
    await page.locator('[data-theme-toggle]').click();
    await page.locator('#itinerary-09>summary').click();
    await page.locator('#itinerary-09').screenshot({path:path.join(require('node:os').tmpdir(), 'dasync-travel-day-mobile.png')});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.locator('[data-currency]').selectOption('JPY');
    await page.evaluate(()=>{window.dispatchEvent(new Event('beforeprint'));window.dispatchEvent(new Event('beforeprint'));});
    assert.equal(await page.locator('details:not([open])').count(),0);
    assert.equal(await page.locator('[data-money-usd]').first().innerText(),'JPY 1,800,000');
    await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));
    assert.equal(await page.locator('details[open]').count(),1);
    await page.setContent(html.replace('<option value="JPY" data-rate="150">JPY · Japanese yen</option>',''));
    assert.equal(await page.locator('[data-currency-control]:visible').count(),0);
    console.log('Passed: currency edge cases, print restoration, route scrolling/print fit, weekdays, copy success/denied/unavailable (clipboard double), expanded mobile day.');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
